//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbKochka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        public int NumberOfClub { get; set; }
        public string AdressOfClub { get; set; }
        public string ContactNumber { get; set; }
    }
}
