//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbKochka
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubCard
    {
        public string CardName { get; set; }
        public decimal CoastMonth { get; set; }
        public decimal CoastHalfYear { get; set; }
        public decimal CoastYear { get; set; }
        public string ChartOfVisits { get; set; }
        public int QuantityOfVisitsPerMonth { get; set; }
    }
}
