//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbKochka
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoachContract
    {
        public int NumberOfClub { get; set; }
        public int ServiceNumber { get; set; }
        public string CardNumber { get; set; }
        public System.DateTime DateOfConclusion { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int QuantityTraining { get; set; }
        public int StillHaveTraining { get; set; }
        public decimal Price { get; set; }
        public int CoachContractId { get; set; }
    }
}
