//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbKochka
{
    using System;

    
    public partial class Employee
    {
        public int NumberOfClub { get; set; }
        public string EmplyeeSecondName { get; set; }
        public string EmplyeeName { get; set; }
        public string EmplyeeMiddleName { get; set; }
        public int ServiceNumber { get; set; }
        public string Name { get; set; }
        public Nullable<int> Experience { get; set; }
    }
}
