//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbKochka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public string VisitorSecondName { get; set; }
        public string VisitorName { get; set; }
        public string VisitorPassport { get; set; }
        public Nullable<System.DateTime> VisitorBDate { get; set; }
        public string CardNumber { get; set; }
    }
}
