//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbKochka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public System.DateTime DateOfVisit { get; set; }
        public int NumberOfClub { get; set; }
        public string CardName { get; set; }
        public string CardNumber { get; set; }
        public int ContractId { get; set; }
    }
}
